package vfs

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// Golden CBOR vectors generated by the Rust `ciborium` encoder (the reference
// server). These pin the Go codec to byte-for-byte parity with the Rust wire
// format; if either side drifts, this test fails.
var (
	vecReqStatFs  = mustHex("66537461744673")
	vecReqGetAttr = mustHex("a16747657441747472a16470617468422f61")
	vecReqRead    = mustHex("a16452656164a36470617468422f66666f6666736574076473697a65191000")
	vecReqFsync   = mustHex("a1654673796e63a26470617468422f66686461746173796e63f5")

	vecRespOk    = mustHex("624f6b")
	vecRespErr   = mustHex("a16345727202")
	vecRespCount = mustHex("a165436f756e7403")
	vecRespAttr  = mustHex("a16441747472aa646b696e6400646d6f64651901a46473697a650563756964006367" +
		"696400656e6c696e6bf6647264657600656174696d65f6656d74696d65f6656374696d65f6")
	vecRespDir = mustHex("a16344697281a2646e616d654161646b696e6400")
)

func mustHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return b
}

// The Go response encoders must produce the exact Rust bytes.
func TestResponseEncodingMatchesRust(t *testing.T) {
	cases := []struct {
		name string
		got  []byte
		want []byte
	}{
		{"Ok", respOk(), vecRespOk},
		{"Err", respErr(2), vecRespErr},
		{"Count", respCount(3), vecRespCount},
		{"Attr", respAttr(FileAttr(0o644, 5)), vecRespAttr},
		{"Dir", respDir([]DirEntry{{Name: []byte("a"), Kind: File}}), vecRespDir},
	}
	for _, c := range cases {
		if !bytes.Equal(c.got, c.want) {
			t.Errorf("%s: got %x, want %x", c.name, c.got, c.want)
		}
	}
}

// The Go request decoder must parse the Rust-encoded requests.
func TestRequestDecodingMatchesRust(t *testing.T) {
	if r, err := decodeRequest(vecReqStatFs); err != nil || r.Op != "StatFs" {
		t.Fatalf("StatFs: op=%q err=%v", opOf(r), err)
	}

	r, err := decodeRequest(vecReqGetAttr)
	if err != nil || r.Op != "GetAttr" || string(r.Path) != "/a" {
		t.Fatalf("GetAttr: %+v err=%v", r, err)
	}

	r, err = decodeRequest(vecReqRead)
	if err != nil || r.Op != "Read" || string(r.Path) != "/f" || r.Offset != 7 || r.Size != 4096 {
		t.Fatalf("Read: %+v err=%v", r, err)
	}

	r, err = decodeRequest(vecReqFsync)
	if err != nil || r.Op != "Fsync" || string(r.Path) != "/f" || !r.Datasync {
		t.Fatalf("Fsync: %+v err=%v", r, err)
	}
}

func opOf(r *request) string {
	if r == nil {
		return "<nil>"
	}
	return r.Op
}
